// data
export const GET_DATA_REQUEST = 'GET_DATA_REQUEST';
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_FAVORITES_SUCCESS = 'GET_FAVORITES_SUCCESS';
export const GET_DATA_FAILURE = 'GET_DATA_FAILURE';
export const POST_NEW_COMMENT = 'POST_NEW_COMMENT';
export const SET_PAGINATION = 'SET_PAGINATION';
// articles
export const NEW_ARTICLE = 'NEW_ARTICLE';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const MARK_AS_FAVORITE_ARTICLE = 'MARK_AS_FAVORITE_ARTICLE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
